export const mockApiData = [
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'json_key_1',
    value:
      'U2FsdGVkX1+mogKJ4wd9gZ2YJ2e7s+mJXtADCnww2B1VfsSBnpyI+Y+Bwz7kpayLjkvSWEMk4iRNo38BtNKFBUrkj5lm7K0my/7xHY1KqvHA5z1msr4yAIsrJETCIl3X',
    valueType: 'json',
    valueEncrypted: true,
    prodEnabled: true,
    devEnabled: true,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'population_auk',
    value: 'U2FsdGVkX1+r7+y9XWTBXxtfCQLUiryxKVyT3C298A0=',
    valueType: 'number',
    valueEncrypted: true,
    prodEnabled: false,
    devEnabled: false,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'key1',
    value: 'value1',
    valueType: 'string',
    prodEnabled: true,
    devEnabled: true,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'key1a',
    value: 'Default Value1',
    valueType: 'string',
    prodEnabled: true,
    devEnabled: false,
  },
  {
    projectName: 'project001',
    groupName: 'group001',
    featureKey: 'encrypt_key_001',
    value:
      'U2FsdGVkX1/r7C9jX5YV0e772hXz0dkdcz3WF+UfLooTybLFCjzVVUGVHxOPhNU0A8nf7lT45sJKD5cVIAHOyA==',
    valueType: 'array',
    valueEncrypted: true,
    prodEnabled: true,
    devEnabled: true,
  },
  {
    projectName: 'project002',
    groupName: 'group002',
    featureKey: 'encrypt_key_002',
    value: 'U2FsdGVkX1+jmy577IqUlWs+ydML3Rs8S6LnAo1wWKG9Gk9Vvjh35rZETsW5D09f',
    valueType: 'array',
    valueEncrypted: true,
    prodEnabled: false,
    devEnabled: true,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'boolean_1',
    value: true,
    valueType: 'boolean',
    prodEnabled: true,
    devEnabled: false,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'boolean_2',
    value: false,
    valueType: 'boolean',
    prodEnabled: true,
    devEnabled: true,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'boolean_003',
    value: true,
    valueType: 'boolean',
    prodEnabled: true,
    devEnabled: true,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'float_key_1',
    value: 23.32,
    valueType: 'number',
    prodEnabled: false,
    devEnabled: false,
  },
  {
    projectName: 'defaultProject',
    groupName: 'defaultGroup',
    featureKey: 'cloudConfigExtraData',
    value: {
      dataRetrievedAt: '2023-10-13T02:18:22.237Z',
      configCount: 10,
    },
    valueType: 'json',
    prodEnabled: true,
    devEnabled: true,
  },
];
